name: CI/CD Pipeline

# Trigger workflow on push to main branch
on:
  push:
    branches: [ "main" ]

# Environment variable for Docker image
env:
  IMAGE_NAME: your-dockerhub-username/nodejs-demo-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests
      - name: Run tests
        run: npm run test

  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Checkout repo again
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .

